# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signuppage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector
from Python_Mini_Proj.GUI.redirect import Ui_RedirectWindow


class Ui_Signup(object):
    def setupUi(self, Signup):
        Signup.setObjectName("Signup")
        Signup.resize(1084, 818)
        Signup.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Signup.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        Signup.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Signup)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 60, 821, 691))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(390, 110, 361, 421))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-radius:40px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 411, 531))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 122, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(430, 150, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(430, 220, 291, 51))
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,255,56);\n"
"padding-left:10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 340, 291, 51))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,255,56);\n"
"padding-left:10px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(480, 400, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: rgba(90, 0, 10, 255);\n"
"    color: rgba(255, 255, 255, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(65, 78, 92, 255); \n"
"}\n"
"\n"
"QPushButton#pushButton:hover {\n"
"    background-color: rgba(105, 118, 132, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(60, 50, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(70, 150, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255,255,255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(80, 250, 231, 231))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(100)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(430, 280, 291, 51))
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,255,56);\n"
"padding-left:10px;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(490, 470, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.clicked.connect(self.insert_user)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setStyleSheet("color: rgba(90, 0, 10, 255);")
        self.label_4.setObjectName("label_4")
        self.label_4.mousePressEvent = self.label_clicked
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEdit_3.raise_()
        self.label_4.raise_()
        Signup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Signup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 26))
        self.menubar.setObjectName("menubar")
        Signup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Signup)
        self.statusbar.setObjectName("statusbar")
        Signup.setStatusBar(self.statusbar)

        self.retranslateUi(Signup)
        QtCore.QMetaObject.connectSlotsByName(Signup)

    def retranslateUi(self, Signup):
        _translate = QtCore.QCoreApplication.translate
        Signup.setWindowTitle(_translate("Signup", "MainWindow"))
        self.label_3.setText(_translate("Signup", "Sign-up"))
        self.lineEdit.setPlaceholderText(_translate("Signup", "Enter Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Signup", "Enter Password"))
        self.pushButton.setText(_translate("Signup", "DONE"))
        self.label_5.setText(_translate("Signup", "Hello There!"))
        self.label_6.setText(_translate("Signup", "Let\'s Create your\n""Profile"))
        self.label_7.setText(_translate("Signup", "👋"))
        self.lineEdit_3.setPlaceholderText(_translate("Signup", "Enter Email"))
        self.label_4.setText(_translate("Signup", "Already a User?"))

    def label_clicked(self, event):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RedirectWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        Signup.close()

    def insert_user(self):
        try:
            # Establish Connection
            connection = mysql.connector.connect(
                host="localhost",
                user="root",
                password="HelloWorld@1234",
                database="handgesture"
            )

            cursor = connection.cursor()

            # Retrieve data from UI
            name = self.lineEdit.text()
            password = self.lineEdit_2.text()
            email = self.lineEdit_3.text()

            # Insert data into the database
            query = "INSERT INTO details (name, password, email) VALUES (%s, %s, %s)"
            cursor.execute(query, (name, password, email))
            connection.commit()

            print("User inserted successfully!")
            self.clear_fields()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("User added successfully!")
            msg.setWindowTitle("Success")
            msg.exec_()
            # Close the signup window after successful signup
            self.window.close()

        except mysql.connector.Error as error:
            print("Failed to connect to MySQL: {}".format(error))
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText(f"Failed to add user: {error}")
            msg.setWindowTitle("Error")
            msg.exec_()
            print("Failed to connect to MySQL: {}".format(error))

        finally:
            if connection.is_connected():
                cursor.close()
                connection.close()
                print("MySQL connection is closed")
    def clear_fields(self):
        self.lineEdit.setText('')
        self.lineEdit_2.setText('')
        self.lineEdit_3.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Signup = QtWidgets.QMainWindow()
    ui = Ui_Signup()
    ui.setupUi(Signup)
    Signup.show()
    sys.exit(app.exec_())
